function ablationResults = singleCellAblationKey(expDate,varargin)
%  singleCellAblationKey - metadata helpful for working with single-cell
%  ablation data
%
% The number of cells ablated were recorded in the fields
% {'nSRLHit','nSRRHit','nSigSTAHit','nNotEye'} 
% number of SR in Left, Right hemisphere, number eye-movement cells, number
% of other cells hit.
% 
% ablationResults.duringAblReg: The correspondence between images taken immediately before/after ablation and 
% movies used to determine where to ablate. A couple of conventions were used for images taken immediately
% before/after ablation when more than one plane was ablated. In some cases
% 1 file contains a concatenation of all attempts in all ablated planes.
% he structure in field _duringAblReg_ stores the folder/file names (either during, duringFirstAblation, duringSecondAblation, etc.) in the field _nameConv_. The structure is of length equal to the number of folders storing the ablation images in _/rawAvgStacks/_ or the number of files stored in _/proc/avgStacks/_. The fields _ablSequenceInds_ and _regImgInds_ are particuarly important for experiments where images from several planes were concatenated into one file. It contains the frames for each plane as separate elements. Otherwise it just stores the total number of frames in each image. 
% The corresponding movies either have a tag _B_ or _inbetween_. This tag is stored in _targetImgCond_. The index of the files that match the damage images is stored in _targetImgInds_.
% Examples: 
% 52319_1 has duringAblReg(2).nameConv = duringSecondAblation. And duringAblReg(2).targetImgCond(1)= B and duringAblReg(2).targetImgInds(1) =1.
% So /rawVideos/f52319_1_B_001.tiff is a movie taken from the second plane ablated whose ablation results are stored in /rawAvgStacks/52319_1/duringFirstAblation/
% and /proc/avgStacks/f52319_1_duringFirstAblation.tif. 
%
%
% 71019_1 has duringAblReg(1).nameConv = duringFirstAblation. duringAblReg(1).ablSequenceInds(2)=6:9 and duringAblReg(1).targetImgCond(2)= B 
% and duringAblReg(1).targetImgInds(2) =3. So /rawVideos/f71019_1_B_003.tif is a movie taken from the second plane ablated whose ablation results
% are stored in /rawAvgStacks/52319_1/duringFirstAblation/ and /proc/avgStacks/f52319_1_duringFirstAblation.tif within frames 6:9. 

options = struct('animalNumber','1');
options = parseNameValueoptions(options,varargin{:});

ablationResults = struct('nSRLHit',0,'nSRRHit',0,'nSigSTAHit',0,'nNotEye',0,'SRHitIDs',[],'BImagesFormDVSequence',false,'procDataEnding',[],'onlineProcDataPath',[],'mapUsedOnline',[]);
% SRL are cells whose dF/F is correlated with time before saccades to the
% left
%
% SRR are cells whose dF/F is correlated with time before saccades to the
% right
%
% sigSTA are cells that are not SR but do have saccade-triggered averages
% where the average at one or more time points is significantly greater than the average at other time points
%
% notEye are cells that are not sigSTA cells.

if strcmp(expDate,'51419')
    ablationResults.nNotEye = 2;
elseif strcmp(expDate,'51519')
    if strcmp(options.animalNumber,'1')
        ablationResults.nNotEye = 2;
    elseif strcmp(options.animalNumber,'2')
        ablationResults.nNotEye = 2;
    end
elseif strcmp(expDate,'51619')
    if strcmp(options.animalNumber,'1')
        ablationResults.nNotEye = 2;
    elseif strcmp(options.animalNumber,'2')
        ablationResults.nSRLHit = 1;
    end
elseif strcmp(expDate,'52219')
    if strcmp(options.animalNumber,'1')
        ablationResults.numAttempted = 4;
        ablationResults.numSuccesses = 4;
        ablationResults.nSRRHit = 1+1+1+1;
        ablationResults.nNotEye = 1+1+1;
        ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f52219_1/firstAnimal/'}};
        ablationResults.duringAblReg = struct('nameConv',{'during'},'regImgInds',{19},'ablSequenceInds',{{1:19}},...
            'targetImgCond',{{'B'}},'targetImgInds',{5});
        ablationResults.SRHitIDs = cell(4,1);
        ablationResults.SRHitIDs{1} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52219_1/firstAnimal/',...
            'XYPosition',[243.6,352.7],'hemiSphereLocation','Left,Contra','ID',[5, 44],'expCond','B',...
            'scAblationPhi',106.27,...
            'targetedXYPosition',[245,355],'targetXYPositionFile','rawAvgStacks/f52219_1/during/f52219_1_targetLocation_001.fig',...
            'summaryEvidenceDamageFile','rawAvgStacks/f52219_1/during/f52219_1_during_019.tif','ablationEvidenceFile','rawAvgStacks/f52219_1/during/f52219_1_during_003.tif',...
            'confidence','strong');
        ablationResults.SRHitIDs{2} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52219_1/firstAnimal/',...
            'XYPosition',[225.8,350.7],'hemiSphereLocation','Left,Contra','ID',[5, 24],'expCond','B',...
            'scAblationPhi',107.9,...
            'targetedXYPosition',[226,354],'targetXYPositionFile','rawAvgStacks/f52219_1/during/f52219_1_targetLocation_002.fig',...
            'summaryEvidenceDamageFile','rawAvgStacks/f52219_1/during/f52219_1_during_019.tif','ablationEvidenceFile','rawAvgStacks/f52219_1/during/f52219_1_during_008.tif',...
            'confidence','weak',...
            'notes','see video in proc/avgStacks/ for best evidence. Ch1 looks like this was 1/3 damaged, ch2 not as much');
        ablationResults.SRHitIDs{3} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52219_1/firstAnimal/',...
            'XYPosition',[208.3301,349.4143],'hemiSphereLocation','Left,Contra','ID',[5, 48],'expCond','B',...
            'scAblationPhi',110.7,...
            'targetedXYPosition',[213,353],'targetXYPositionFile','rawAvgStacks/f52219_1/during/f52219_1_targetLocation_003.fig',...
            'summaryEvidenceDamageFile','rawAvgStacks/f52219_1/during/f52219_1_during_019.tif','ablationEvidenceFile','rawAvgStacks/f52219_1/during/f52219_1_during_008.tif',...
            'confidence','OK',...
            'notes','see video in proc/avgStacks/ for best evidence.');
        ablationResults.SRHitIDs{4} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52219_1/firstAnimal/',...
            'XYPosition',[240.3788,400.8878],'hemiSphereLocation','Left,Contra','ID',[5, 61],'expCond','B',...
            'scAblationPhi',133.7,...
            'targetedXYPosition',[240,403],'targetXYPositionFile','rawAvgStacks/f52219_1/during/f52219_1_targetLocation_004.fig',...
            'summaryEvidenceDamageFile','rawAvgStacks/f52219_1/during/f52219_1_during_019.tif','ablationEvidenceFile','rawAvgStacks/f52219_1/during/f52219_1_during_010.tif',...
            'confidence','strong');
        
    elseif strcmp(options.animalNumber,'2')
        ablationResults.numAttempted = 4;
        ablationResults.numSuccesses = 4;
        ablationResults.nNotEye = 8;
        ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f52219_2/'}};
        ablationResults.duringAblReg = struct('nameConv',{'during'},'regImgInds',{9},'ablSequenceInds',{{1:9}},...
            'targetImgCond',{{'B'}},'targetImgInds',{5});
    end
elseif strcmp(expDate,'52319')
    if strcmp(options.animalNumber,'1')
        ablationResults.nSRRHit = 1+1+1+1;
        ablationResults.nNotEye = 1+2+2+1;
        ablationResults.nSigSTAHit = 1;
        ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f52319_1/animal1fifthPlane/'},{'proc/analysisDuringExperiment/f52319_1/animal1sixthPlane/'}};
        ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation','duringSecondAblation'},'regImgInds',{16,12},'ablSequenceInds',{{1:16},{1:12}},...
            'targetImgCond',{{'B'},{'inbetween'}},'targetImgInds',{9,1});
        ablationResults.SRHitIDs = cell(4,1);
        ablationResults.SRHitIDs{1} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52319_1/animal1fifthPlane/',...
            'XYPosition',[181.888,208.360],'hemiSphereLocation','Right Ipsi','ID',[9,191],'expCond','B',...
            'scAblationPhi',-172.8,...
            'targetedXYPosition',[[178,208];[184,206];[184,206]],'targetXYPositionFile','rawAvgStacks/f52319_1/duringFirstAblation/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f52319_1/duringFirstAblation/f52319_1_during_016.tif','ablationEvidenceFile','rawAvgStacks/f52219_1/duringFirstAblation/f52319_1_during_007.tif',...
            'confidence','good: would be stronger if less drift');
        
        ablationResults.SRHitIDs{2} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52319_1/animal1fifthPlane/',...
            'XYPosition',[179.596,440.738],'hemiSphereLocation','Left Contra','ID',[9,170],'expCond','B',...
            'scAblationPhi',6.3,...
            'targetedXYPosition',[[182,436];[183,438];[185,434];[184,437];[184,437]],'targetXYPositionFile','rawAvgStacks/f52319_1/duringFirstAblation/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f52319_1/duringFirstAblation/f52319_1_during_016.tif','ablationEvidenceFile','rawAvgStacks/f52219_1/duringFirstAblation/f52319_1_during_016.tif',...
            'confidence','strong');
        
        ablationResults.SRHitIDs{3} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52319_1/animal1sixthPlane/',...
            'XYPosition',[151.401,337.172],'hemiSphereLocation','Left Contra','ID',[1,64],'expCond','inbetween',...
            'scAblationPhi',126.7,...
            'targetedXYPosition',[[155,335];[147,338]],'targetXYPositionFile','rawAvgStacks/f52319_1/duringSecondAblation/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f52319_1/duringSecondAblation/f52319_1_during_012.tif','ablationEvidenceFile','rawAvgStacks/f52319_1/duringSecondAblation/f52319_1_during_012.tif',...
            'confidence','strong');
        
        ablationResults.SRHitIDs{4} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52319_1/animal1sixthPlane/',...
            'XYPosition',[222.943,201.850],'hemiSphereLocation','Right Ipsi','ID',[1,169],'expCond','inbetween',...
            'scAblationPhi',164.6,...
            'targetedXYPosition',[[228,202];[229,202];[220,200]],'targetXYPositionFile','rawAvgStacks/f52319_1/duringSecondAblation/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f52319_1/duringSecondAblation/f52319_1_during_012.tif','ablationEvidenceFile','rawAvgStacks/f52319_1/duringSecondAblation/f52319_1_during_011.tif',...
            'confidence','strong');
    elseif strcmp(options.animalNumber,'2')
        ablationResults.nNotEye = 6+3;
        ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f52319_2/animal2firstPlane/'},{'proc/analysisDuringExperiment/f52319_2/animal2secondPlane/'}};
        ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation','duringSecondAblation'},'regImgInds',{7,10},'ablSequenceInds',{{1:7},{1:10}},...
            'targetImgCond',{{'B'},{'inbetween'}},'targetImgInds',{1,1});
    end
elseif strcmp(expDate,'52419')
    ablationResults.nSRRHit = 1+1+1+1+1+1;
    ablationResults.nNotEye = 1+1+2+3;
     ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f52419_1/firstPlane/'},...
         {[]},...
         {'proc/analysisDuringExperiment/f52419_1/thirdPlane/'},...
         {'proc/analysisDuringExperiment/f52419_1/fourthPlane/'},...
         {'proc/analysisDuringExperiment/f52419_1/fifthPlane/'}};
    ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation','duringSecondAblation','duringThirdAblation','duringFourthAblation','duringFifthAblation'},...
        'regImgInds',{2,2,10,16,13},'ablSequenceInds',{{1:2},{1:2},{1:10},{1:16},{1:13}},...
        'targetImgCond',{{'B'},{'inbetween'},{'inbetween'},{'inbetween'},{'inbetween'}},'targetImgInds',{1,1,3,5,7});
    ablationResults.SRHitIDs = cell(6,1);
    ablationResults.SRHitIDs{1} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52419_1/firstPlane/',...
        'XYPosition',[303.232,180.169],'hemiSphereLocation','Right Ipsi','ID',[1,5],'expCond','B',...
        'scAblationPhi',90.4,...
        'targetedXYPosition',[299,182],'targetXYPositionFile','rawAvgStacks/f52419_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f52419_1/duringFirstAblation/f52419_1_during_002.tif','ablationEvidenceFile','rawAvgStacks/f52419_1/duringFirstAblation/f52419_1_during_002.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{2} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52419_1/thirdPlane/',...
        'XYPosition',[21.804,340.725],'hemiSphereLocation','Left Contra','ID',[3,45],'expCond','inbetween',...
        'scAblationPhi',103.1,...
        'targetedXYPosition',[[23,342];[22,345]],'targetXYPositionFile','rawAvgStacks/f52419_1/duringThirdAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f52419_1/duringThirdAblation/f52419_1_during_010.tif','ablationEvidenceFile','rawAvgStacks/f52419_1/duringThirdAblation/f52419_1_during_006.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{3} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52419_1/thirdPlane/',...
        'XYPosition',[352.266,364.391],'hemiSphereLocation','Left Contra','ID',[3,86],'expCond','inbetween',...
        'scAblationPhi',68.7,...
        'targetedXYPosition',[[350,363],[352,366],[351,368]],'targetXYPositionFile','rawAvgStacks/f52419_1/duringThirdAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f52419_1/duringThirdAblation/f52419_1_during_010.tif','ablationEvidenceFile','rawAvgStacks/f52419_1/duringThirdAblation/f52419_1_during_010.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{4} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52419_1/fourthPlane/',...
        'XYPosition',[108.565,195.139],'hemiSphereLocation','Right Ipsi','ID',[5,19],'expCond','inbetween',...
        'scAblationPhi',51.8,...
        'targetedXYPosition',[[106,196];[106,194]],'targetXYPositionFile','rawAvgStacks/f52419_1/duringFourthAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f52419_1/duringFourthAblation/f52419_1_during_016.tif','ablationEvidenceFile','rawAvgStacks/f52419_1/duringFourthAblation/f52419_1_during_013.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{5} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52419_1/fourthPlane/',...
        'XYPosition',[120.174,247.246],'hemiSphereLocation','Right Ipsi','ID',[5,32],'expCond','inbetween',...
        'scAblationPhi',166.3,...
        'targetedXYPosition',[[123,247];[121,247];[122,247];[120,246]],'targetXYPositionFile','rawAvgStacks/f52419_1/duringFourthAblation',...
        'summaryEvidenceDamageFile','rawAvgStacks/f52419_1/duringFourthAblation/f52419_1_during_016.tif','ablationEvidenceFile','rawAvgStacks/f52419_1/duringFourthAblation/f52419_1_during_016.tif',...
        'confidence','good: would be stronger if less drift');
    
    ablationResults.SRHitIDs{6} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52419_1/fifthPlane/',...
        'XYPosition',[32.217,371.597],'hemiSphereLocation','Left Contra','ID',[7,7],'expCond','inbetween',...
        'scAblationPhi',114.6,...
        'targetedXYPosition',[[33,373];[33,373];[33,373];[26,372];[33,373];[32,371]],'targetXYPositionFile','rawAvgStacks/f52419_1/duringFifthAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f52419_1/duringFifthAblation/f52419_1_during_013.tif','ablationEvidenceFile','rawAvgStacks/f52419_1/duringFifthAblation/f52419_1_during_012.tif',...
        'confidence','weak: would be stronger if brighter');
elseif strcmp(expDate,'52919')
    ablationResults.nSRRHit = 1;
    ablationResults.nSRLHit = 3;
    ablationResults.nNotEye = 2+1+2+4+2+2;
    ablationResults.nSigSTAHit = 1;
     ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f52919_1/fourthPlane/'},...
         {'proc/analysisDuringExperiment/f52919_1/sixthPlane/'},...
         {'proc/analysisDuringExperiment/f52919_1/sixthPlane/'}};
    ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation','duringSecondAblation','duringThirdAblation'},'regImgInds',{3,2,5},'ablSequenceInds',{{1:3},{1:2},{1:5}},...
        'targetImgCond',{{'B'},{'inbetween'},{'inbetween'}},'targetImgInds',{7,1,3});
    ablationResults.SRHitIDs = cell(4,1);
    
%     ablationResults.SRHitIDs{1} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52919_1/fourthPlane/',...
%         'XYPosition',[3.927,100.924],'hemiSphereLocation','Right Ipsi','ID',[7,21],'expCond','B',...
%         'scAblationPhi',82.7,...
%         'targetedXYPosition',[13,106],'targetXYPositionFile','rawAvgStacks/f52919_1/duringFirstAblation/',...
%         'summaryEvidenceDamageFile','rawAvgStacks/f52919_1/duringFirstAblation/f52919_1_during_003.tif','ablationEvidenceFile','rawAvgStacks/f52919_1/duringFirstAblation/f52919_1_during_002.tif',...
%         'confidence','good: would be stronger if less drift');
    
    ablationResults.SRHitIDs{1} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52919_1/fourthPlane/',...
        'XYPosition',[33.142,65.185],'hemiSphereLocation','Right Ipsi','ID',[7,9],'expCond','B',...
        'scAblationPhi',124.6,...
        'targetedXYPosition',[41,70],'targetXYPositionFile','rawAvgStacks/f52919_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f52919_1/duringFirstAblation/f52919_1_during_003.tif','ablationEvidenceFile','rawAvgStacks/f52919_1/duringFirstAblation/f52919_1_during_003.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{2} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52919_1/sixthPlane/',...
        'XYPosition',[222.065,346.374],'hemiSphereLocation','Left Ipsi','ID',[3,232],'expCond','inbetween',...
        'scAblationPhi',29.5,...
        'targetedXYPosition',[221,344],'targetXYPositionFile','rawAvgStacks/f52919_1/duringThirdAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f52919_1/duringThirdAblation/f52919_1_during_005.tif','ablationEvidenceFile','rawAvgStacks/f52919_1/duringThirdAblation/f52919_1_during_002.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{3} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52919_1/sixthPlane/',...
        'XYPosition',[111.656,347.873],'hemiSphereLocation','Left Ipsi','ID',[3,205],'expCond','inbetween',...
        'scAblationPhi',32.8,...
        'targetedXYPosition',[108,346],'targetXYPositionFile','rawAvgStacks/f52919_1/duringThirdAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f52919_1/duringThirdAblation/f52919_1_during_005.tif','ablationEvidenceFile','rawAvgStacks/f52919_1/duringThirdAblation/f52919_1_during_003.tif',...
        'confidence','strong');
    
%     ablationResults.SRHitIDs{5} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52919_1/sixthPlane/',...
%         'XYPosition',[146.619,350.539],'hemiSphereLocation','Left Ipsi','ID',[3,209],'expCond','inbetween',...
%         'scAblationPhi',85.0,...
%         'targetedXYPosition',[138,351],'targetXYPositionFile','rawAvgStacks/f52919_1/duringThirdAblation/',...
%         'summaryEvidenceDamageFile','rawAvgStacks/f52919_1/duringThirdAblation/f52919_1_during_005.tif','ablationEvidenceFile','rawAvgStacks/f52919_1/duringThirdAblation/f52919_1_during_004.tif',...
%         'confidence','weak: this cell looks like it was not hit. I have corrected the above field');
    
    ablationResults.SRHitIDs{4} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f52919_1/sixthPlane/',...
        'XYPosition',[65.388,357.031],'hemiSphereLocation','Left Ipsi','ID',[3,197],'expCond','inbetween',...
        'scAblationPhi',95.2,...
        'targetedXYPosition',[57,358],'targetXYPositionFile','rawAvgStacks/f52919_1/duringThirdAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f52919_1/duringThirdAblation/f52919_1_during_005.tif','ablationEvidenceFile','rawAvgStacks/f52919_1/duringThirdAblation/f52919_1_during_005.tif',...
        'confidence','strong');
    
elseif strcmp(expDate,'53019')
    ablationResults.nSRLHit = 1+1+1+1;
    ablationResults.nNotEye = 3+2+1+2+1;
    ablationResults.nSigSTAHit = 0;
    ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f53019_1/sixthPlane/','proc/analysisDuringExperiment/f53019_1/firstPlane/'}};
    ablationResults.duringAblReg = struct('nameConv',{'during'},'regImgInds',{[12,14]},'ablSequenceInds',{[{1:12},{13:14}]},...
        'targetImgCond',{[{'B'},{'B'}]},'targetImgInds',{[11,1]});
    ablationResults.SRHitIDs = cell(4,1);
    
    ablationResults.SRHitIDs{1} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f53019_1/sixthPlane/',...
        'XYPosition',[175.263,360.261],'hemiSphereLocation','Left Ipsi','ID',[11,238],'expCond','B',...
        'scAblationPhi',19.0,...
        'targetedXYPosition',[[175,361];[177,344];[177,362];[184,341];[181,344]],'targetXYPositionFile','rawAvgStacks/f53019_1/during/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f53019_1/during/f53019_1_during_014.tif','ablationEvidenceFile','rawAvgStacks/f53019_1/during/f53019_1_during_009.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{2} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f53019_1/sixthPlane/',...
        'XYPosition',[180.636,344.721],'hemiSphereLocation','Left Ipsi','ID',[11,203],'expCond','B',...
        'scAblationPhi',21.0,...
        'targetedXYPosition',[[181,360]],'targetXYPositionFile','rawAvgStacks/f53019_1/during/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f53019_1/during/f53019_1_during_014.tif','ablationEvidenceFile','rawAvgStacks/f53019_1/during/f53019_1_during_010.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{3} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f53019_1/sixthPlane/',...
        'XYPosition',[261.608,360.317],'hemiSphereLocation','Left Ipsi','ID',[11,183],'expCond','B',...
        'scAblationPhi',69.8,...
        'targetedXYPosition',[[264,366];[251,364]],'targetXYPositionFile','rawAvgStacks/f53019_1/during/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f53019_1/during/f53019_1_during_014.tif','ablationEvidenceFile','rawAvgStacks/f53019_1/during/f53019_1_during_012.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{4} = struct('procDataEnding','','onlineProcDataPath','proc/analysisDuringExperiment/f53019_1/firstPlane/',...
        'XYPosition',[402.129,332.864],'hemiSphereLocation','Left Ipsi','ID',[1,141],'expCond','B',...
        'scAblationPhi',57.8,...
        'targetedXYPosition',[[463,341]],'targetXYPositionFile','rawAvgStacks/f53019_1/during/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f53019_1/during/f53019_1_during_014.tif','ablationEvidenceFile','rawAvgStacks/f53019_1/during/f53019_1_during_014.tif',...
        'confidence','strong');
    
elseif strcmp(expDate,'6519')
    if strcmp(options.animalNumber,'1')
        ablationResults.nSRLHit = 1;
        ablationResults.nSigSTAHit = 1;
        ablationResults.procDataEnding = {{'8'}};
        ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f6519_1/firstPlane/'}};
        ablationResults.duringAblReg = struct('nameConv',{'during'},'regImgInds',{2},'ablSequenceInds',{{1:2}},...
            'targetImgCond',{{'B'}},'targetImgInds',{17});
    elseif strcmp(options.animalNumber,'2')
        ablationResults.nNotEye = 4+6;
        ablationResults.mapUsedOnline = {{[]},{'proc/analysisDuringExperiment/f6519_2/fifthPlane/f6519_2_BMAP1.fig'}};
        ablationResults.procDataEnding = {{'2'},{[]}}; % anticCC is missing for '2'
        ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f6519_2/sixthPlane/'},{[]}}; % anticCC is missing for 'proc/analysisDuringExperiment/f6519_2/fifthPlane/'
        ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation','duringSecondAblation'},'regImgInds',{6,11},'ablSequenceInds',{{1:6},{1:11}},...
            'targetImgCond',{{'B'},{'inbetween'}},'targetImgInds',{14,1});
    end
elseif strcmp(expDate,'6619')
    if strcmp(options.animalNumber,'1')
        ablationResults.nNotEye = 6+4;
        ablationResults.procDataEnding = {{'3'},{'4'}};
        ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f6619_1/fifthPlane/'},{'proc/analysisDuringExperiment/f6619_1/fourthPlane/'}};
        ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation','duringSecondAblation'},'regImgInds',{8,7},'ablSequenceInds',{{1:8},{1:7}},...
            'targetImgCond',{{'B'},{'inbetween'}},'targetImgInds',{11,1});
    elseif strcmp(options.animalNumber,'2')
        ablationResults.nSRRHit = 1+1+1+1+1;
        ablationResults.nNotEye = 2+3+1+1+1+2;
        ablationResults.nSigSTAHit = 1;
        ablationResults.procDataEnding = {{'13','10'}};
        ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f6619_2/thirdPlane/','proc/analysisDuringExperiment/f6619_2/secondPlane/'}};
        ablationResults.duringAblReg = struct('nameConv',{'during'},'regImgInds',{[7,20]},'ablSequenceInds',{[{1:7},{8:20}]},...
            'targetImgCond',{[{'B'},{'B'}]},'targetImgInds',{[13,10]});
        ablationResults.SRHitIDs = cell(5,1);
        ablationResults.SRHitIDs{1} = struct('procDataEnding','13','onlineProcDataPath','proc/analysisDuringExperiment/f6619_2/thirdPlane/',...
            'XYPosition',[359.014,248.188],'hemiSphereLocation','Right Ipsi','ID',[13,99],'expCond','B',...
            'scAblationPhi',56.4,...
            'targetedXYPosition',[[357,251];[357,251];[357,251]],'targetXYPositionFile','rawAvgStacks/f6619_2/during/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f6619_2/during/f6619_2_during_007.tif','ablationEvidenceFile','rawAvgStacks/f6619_2/during/f6619_2_duringNAN_NAN.tif',...
            'confidence','strong');
        
        ablationResults.SRHitIDs{2} = struct('procDataEnding','13','onlineProcDataPath','proc/analysisDuringExperiment/f6619_2/thirdPlane/',...
            'XYPosition',[447.321,374.406],'hemiSphereLocation','Left Contra','ID',[13,163],'expCond','B',...
            'scAblationPhi',31.4,...
            'targetedXYPosition',[[445,375]],'targetXYPositionFile','rawAvgStacks/f6619_2/during/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f6619_2/during/f6619_2_during_007.tif','ablationEvidenceFile','rawAvgStacks/f6619_2/during/f6619_2_duringNAN_NAN.tif',...
            'confidence','strong');
        
        ablationResults.SRHitIDs{3} = struct('procDataEnding','10','onlineProcDataPath','proc/analysisDuringExperiment/f6619_2/secondPlane/',...
            'XYPosition',[239.062,200.171],'hemiSphereLocation','Right Ipsi','ID',[10,91],'expCond','B',...
            'scAblationPhi',61.8,...
            'targetedXYPosition',[[234,203];[230,202];[231,204];[231,204]],'targetXYPositionFile','rawAvgStacks/f6619_2/during/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f6619_2/during/f6619_2_duringSecondVeneer10_013.tif','ablationEvidenceFile','rawAvgStacks/f6619_2/during/f6619_2_duringNAN_NAN.tif',...
            'confidence','strong');
        
        ablationResults.SRHitIDs{4} = struct('procDataEnding','10','onlineProcDataPath','proc/analysisDuringExperiment/f6619_2/secondPlane/',...
            'XYPosition',[351.038,227.903],'hemiSphereLocation','Right Ispsi','ID',[10,25],'expCond','B',...
            'scAblationPhi',91.9,...
            'targetedXYPosition',[[345,232];[345,232];[361,230]],'targetXYPositionFile','rawAvgStacks/f6619_2/during/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f6619_2/during/f6619_2_duringSecondVeneer10_013.tif','ablationEvidenceFile','rawAvgStacks/f6619_2/during/f6619_2_duringNAN_NAN.tif',...
            'confidence','strong');
        
        ablationResults.SRHitIDs{5} = struct('procDataEnding','10','onlineProcDataPath','proc/analysisDuringExperiment/f6619_2/secondPlane/',...
            'XYPosition',[172.493,336.470],'hemiSphereLocation','Left Contra','ID',[10,90],'expCond','B',...
            'scAblationPhi',114.6,...
            'targetedXYPosition',[[184,334];[175,334];[173,337];[170,347];[173,341]],'targetXYPositionFile','rawAvgStacks/f6619_2/during/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f6619_2/during/f6619_2_duringSecondVeneer10_013.tif','ablationEvidenceFile','rawAvgStacks/f6619_2/during/f6619_2_duringSecondVeneer10_013.tif',...
            'confidence','good: would be better if less drift occurred during the ablations, however still possible to view that cell was hit');
    end
elseif strcmp(expDate,'61219')
    ablationResults.nNotEye = 1+2+3+2+3+1+2;
    ablationResults.nSRRHit = 1+1+1+1+1+1;
    ablationResults.nSRLHit = 1;
    ablationResults.nSigSTAHit = 1;
    ablationResults.procDataEnding = {{'14'},{'16'}};
    ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f61219_1/'},{'proc/analysisDuringExperiment/f61219_1/'}};
    ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation','duringSecondAblation'},'regImgInds',{9,18},'ablSequenceInds',{{1:9},{1:18}},...
        'targetImgCond',{{'B'},{'inbetween'}},'targetImgInds',{14,2});
    ablationResults.SRHitIDs = cell(6,1);
    ablationResults.SRHitIDs{1} = struct('procDataEnding','14','onlineProcDataPath','proc/analysisDuringExperiment/f61219_1/',...
        'XYPosition',[396.249,219.248],'hemiSphereLocation','Right Ipsi','ID',[14,130],'expCond','B',...
        'scAblationPhi',85.7,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f61219_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f61219_1/duringFirstAblation/f61219_1_during_009.tif','ablationEvidenceFile','rawAvgStacks/f61219_1/duringFirstAblation/f61219_1_NaN.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{2} = struct('procDataEnding','14','onlineProcDataPath','proc/analysisDuringExperiment/f61219_1/',...
        'XYPosition',[106.817,182.444],'hemiSphereLocation','Right Ipsi','ID',[14,167],'expCond','B',...
        'scAblationPhi',38.4,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f61219_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f61219_1/duringFirstAblation/f61219_1_during_009.tif','ablationEvidenceFile','rawAvgStacks/f61219_1/duringFirstAblation/f61219_1_NaN.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{3} = struct('procDataEnding','14','onlineProcDataPath','proc/analysisDuringExperiment/f61219_1/',...
        'XYPosition',[369.354,185.303],'hemiSphereLocation','Right Ipsi','ID',[14,79],'expCond','B',...
        'scAblationPhi',77.0,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f61219_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f61219_1/duringFirstAblation/f61219_1_during_009.tif','ablationEvidenceFile','rawAvgStacks/f61219_1/duringFirstAblation/f61219_1_NaN.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{4} = struct('procDataEnding','16','onlineProcDataPath','proc/analysisDuringExperiment/f61219_1/',...
        'XYPosition',[189,284],'hemiSphereLocation','Right Contra','ID',[2,176],'expCond','inbetween',...
        'scAblationPhi',NaN,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f61219_1/duringSecondAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f61219_1/duringSecondAblation/f61219_1_during_018.tif','ablationEvidenceFile','rawAvgStacks/f61219_1/duringSecondAblation/f61219_1_NaN.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{5} = struct('procDataEnding','16','onlineProcDataPath','proc/analysisDuringExperiment/f61219_1/',...
        'XYPosition',[440.055,261.706],'hemiSphereLocation','Left Ipsi','ID',[2,61],'expCond','inbetween',...
        'scAblationPhi',98.7,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f61219_1/duringSecondAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f61219_1/duringSecondAblation/f61219_1_during_018.tif','ablationEvidenceFile','rawAvgStacks/f61219_1/duringSecondAblation/f61219_1_NaN.tif',...
        'confidence','strong');
    
%     ablationResults.SRHitIDs{6} = struct('procDataEnding','16','onlineProcDataPath','proc/analysisDuringExperiment/f61219_1/',...
%         'XYPosition',[83.195,180.127],'hemiSphereLocation','Right Ipsi','ID',[2,123],'expCond','inbetween',...
%         'scAblationPhi',15.123,...
%         'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f61219_1/duringSecondAblation/',...
%         'summaryEvidenceDamageFile','rawAvgStacks/f61219_1/duringSecondAblation/f61219_1_during_018.tif','ablationEvidenceFile','rawAvgStacks/f61219_1/duringSecondAblation/f61219_1_NaN.tif',...
%         'confidence','strong');
    
    ablationResults.SRHitIDs{6} = struct('procDataEnding','16','onlineProcDataPath','proc/analysisDuringExperiment/f61219_1/',...
        'XYPosition',[209.445,173.860],'hemiSphereLocation','Right Ipsi','ID',[2,189],'expCond','inbetween',...
        'scAblationPhi',117.9,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f61219_1/duringSecondAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f61219_1/duringSecondAblation/f61219_1_during_018.tif','ablationEvidenceFile','rawAvgStacks/f61219_1/duringSecondAblation/f61219_1_NaN.tif',...
        'confidence','strong');
elseif strcmp(expDate,'61919')
    % THE NMF FILES WERE SAVED IN proc/analysisDuringExperiment/f61919_1/ WITH 
    % THE ENDINGS (2,5,4) BUT NOT THE STA AND CC ANALYSES
    ablationResults.nNotEye = 5+9+11;
    ablationResults.nSRRHit = 0;
    ablationResults.nSigSTAHit = 0;
    ablationResults.mapUsedOnline = {{'proc/analysisDuringExperiment/f61919_1/f61919_1_beforeMAP_2.fig'},{'proc/analysisDuringExperiment/f61919_1/f61919_1_beforeMAP_5.fig'},{'proc/analysisDuringExperiment/f61919_1/f61919_1_beforeMAP_4.fig'}};
    ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation','duringSecondAblation','duringThirdAblation'},'regImgInds',{5,12,7},'ablSequenceInds',{{1:5},{1:12},{1:7}},...
        'targetImgCond',{{'B'},{'B'},{'B'}},'targetImgInds',{2,5,4});
elseif strcmp(expDate,'62019')
    if strcmp(options.animalNumber,'1')
        ablationResults.BImagesFormDVSequence = true;
         ablationResults.nSigSTAHit = 0;
        ablationResults.nNotEye = 9+2+3;
        ablationResults.procDataEnding = {{'_1'},{'_3'},{'_5'}};
        ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f62019_1/before/'},{'proc/analysisDuringExperiment/f62019_1/before/'},{'proc/analysisDuringExperiment/f62019_1/before/'}};
        ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation','duringSecondAblation','duringThirdAblation'},'regImgInds',{2,5,10},'ablSequenceInds',{{1:2},{1:5},{1:10}},...
            'targetImgCond',{{'B'},{'B'},{'B'}},'targetImgInds',{1,3,5});
    elseif strcmp(options.animalNumber,'2')
        ablationResults.BImagesFormDVSequence = true;
        ablationResults.procDataEnding = {{'_1'},{'_2'}};
        ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f62019_2/before/'},{'proc/analysisDuringExperiment/f62019_2/before/'}};
        ablationResults.nNotEye = 10+4;
        ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation','duringSecondAblation'},'regImgInds',{8,9},'ablSequenceInds',{{1:8},{1:9}},...
            'targetImgCond',{{'B'},{'B'}},'targetImgInds',{1,2});
    end
elseif strcmp(expDate,'7119')
    ablationResults.nSRLHit = 1+1+1+1;
    ablationResults.nNotEye = 4+1+2+2;
    ablationResults.nSigSTAHit = 0;
    ablationResults.procDataEnding = {{'9','8'}};
    ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f7119_1/','proc/analysisDuringExperiment/f7119_1/'}};
    ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation'},'regImgInds',{[4,6]},'ablSequenceInds',{[{1:4},{5:6}]},...
        'targetImgCond',{[{'B'},{'B'}]},'targetImgInds',{[9,8]});
    ablationResults.SRHitIDs = cell(4,1);
    ablationResults.SRHitIDs{1} = struct('procDataEnding','9','onlineProcDataPath','proc/analysisDuringExperiment/f7119_1/',...
        'XYPosition',[181.914,342.600],'hemiSphereLocation','Left Ipsi','ID',[9,129],'expCond','B',...
        'scAblationPhi',96.0,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f7119_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f7119_1/duringFirstAblation/f7119_1_during_004.tif','ablationEvidenceFile','rawAvgStacks/f7119_1/duringFirstAblation/f7119_1_NaN.tif',...
        'summaryEvidenceFigName','f7119_1_duringFirstAblation_1-4.fig',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{2} = struct('procDataEnding','9','onlineProcDataPath','proc/analysisDuringExperiment/f7119_1/',...
        'XYPosition',[129.429,342.546],'hemiSphereLocation','Left Ipsi','ID',[9,90],'expCond','B',...
        'scAblationPhi',88.3,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f7119_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f7119_1/duringFirstAblation/f7119_1_during_004.tif','ablationEvidenceFile','rawAvgStacks/f7119_1/duringFirstAblation/f7119_1_NaN.tif',...
        'summaryEvidenceFigName','f7119_1_duringFirstAblation_1-4.fig',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{3} = struct('procDataEnding','9','onlineProcDataPath','proc/analysisDuringExperiment/f7119_1/',...
        'XYPosition',[361.224,316.080],'hemiSphereLocation','Left Ipsi','ID',[9,49],'expCond','B',...
        'scAblationPhi',100.5,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f7119_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f7119_1/duringFirstAblation/f7119_1_during_004.tif','ablationEvidenceFile','rawAvgStacks/f7119_1/duringFirstAblation/f7119_1_NaN.tif',...
        'summaryEvidenceFigName','f7119_1_duringFirstAblation_1-4.fig',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{4} = struct('procDataEnding','8','onlineProcDataPath','proc/analysisDuringExperiment/f7119_1/',...
        'XYPosition',[339.388,291.888],'hemiSphereLocation','Left Ipsi','ID',[8,63],'expCond','B',...
        'scAblationPhi',98.2,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f7119_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f7119_1/duringFirstAblation/f7119_1_during_006.tif','ablationEvidenceFile','rawAvgStacks/f7119_1/duringFirstAblation/f7119_1_NaN.tif',...
        'summaryEvidenceFigName','f7119_1_duringFirstAblation_5-6.fig',...
        'confidence','strong');
    
    ablationResults.targetedXYPosition = cell(2,1);
    ablationResults.targetedXYPosition{1} = struct('summaryEvidenceFigName','f7119_1_duringFirstAblation_1-4.fig','targetedXYPosition',[[238,304];[187,307];[419,278]]);
    ablationResults.targetedXYPosition{2} = struct('summaryEvidenceFigName','f7119_1_duringFirstAblation_5-6.fig','targetedXYPosition',[406,255]);
    
    
elseif strcmp(expDate,'7319')
    ablationResults.nSRLHit = 1+1+1+1+1;
    ablationResults.nNotEye = 1+3+1+2+2+3;    
    ablationResults.nSigSTAHit = 0;
    ablationResults.nSRRHit = 1;
    ablationResults.procDataEnding = {{'4','5','1'}};
    ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f7319_1/','proc/analysisDuringExperiment/f7319_1/','proc/analysisDuringExperiment/f7319_1/'}};
    ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation'},'regImgInds',{[10,13,16]},'ablSequenceInds',{[{1:10},{11:13},{14:16}]},...
        'targetImgCond',{[{'B'},{'B'},{'B'}]},'targetImgInds',{[4,5,1]});
    ablationResults.SRHitIDs = cell(6,1);
    ablationResults.SRHitIDs{1} = struct('procDataEnding','4','onlineProcDataPath','proc/analysisDuringExperiment/f7319_1/',...
        'XYPosition',[312.410,323.646],'hemiSphereLocation','Left Ipsi','ID',[4,61],'expCond','B',...
        'scAblationPhi',152.8,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f7319_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_during_009.tif','ablationEvidenceFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_NaN.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{2} = struct('procDataEnding','4','onlineProcDataPath','proc/analysisDuringExperiment/f7319_1/',...
        'XYPosition',[321.286,184.350],'hemiSphereLocation','Right Contra','ID',[4,124],'expCond','B',...
        'scAblationPhi',92.3,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f7319_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_during_009.tif','ablationEvidenceFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_NaN.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{3} = struct('procDataEnding','4','onlineProcDataPath','proc/analysisDuringExperiment/f7319_1/',...
        'XYPosition',[91.234,326.978],'hemiSphereLocation','Left Contra','ID',[4,59],'expCond','B',...
        'scAblationPhi',126.7,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f7319_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_during_009.tif','ablationEvidenceFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_NaN.tif',...
        'confidence','strong');
    
    %     ablationResults.SRHitIDs{4} = struct('procDataEnding','4','onlineProcDataPath','proc/analysisDuringExperiment/f7319_1/',...
    %             'XYPosition',[103.551,339.993],'hemiSphereLocation','Left Ipsi','ID',[4,136],'expCond','B',...
    %             'scAblationPhi',73.8,...
    %             'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f7319_1/duringFirstAblation/',...
    %             'summaryEvidenceDamageFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_during_009.tif','ablationEvidenceFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_NaN.tif',...
    %             'confidence','weak,good,strong');
    
    ablationResults.SRHitIDs{4} = struct('procDataEnding','5','onlineProcDataPath','proc/analysisDuringExperiment/f7319_1/',...
        'XYPosition',[67.839,200.210],'hemiSphereLocation','Right Contra','ID',[5,199],'expCond','B',...
        'scAblationPhi',120.7,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f7319_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_during_013.tif','ablationEvidenceFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_during_013.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{5} = struct('procDataEnding','1','onlineProcDataPath','proc/analysisDuringExperiment/f7319_1/',...
        'XYPosition',[339.269,347.813],'hemiSphereLocation','Left Ipsi','ID',[1,66],'expCond','B',...
        'scAblationPhi',78.7,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f7319_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_during_016.tif','ablationEvidenceFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_NaN.tif',...
        'confidence','strong');
    
    ablationResults.SRHitIDs{6} = struct('procDataEnding','1','onlineProcDataPath','proc/analysisDuringExperiment/f7319_1/',...
        'XYPosition',[160.147,340.116],'hemiSphereLocation','Left Ipsi','ID',[1,144],'expCond','B',...
        'scAblationPhi',89.9,...
        'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f7319_1/duringFirstAblation/',...
        'summaryEvidenceDamageFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_during_016.tif','ablationEvidenceFile','rawAvgStacks/f7319_1/duringFirstAblation/f7319_1_NaN.tif',...
        'confidence','strong');
elseif strcmp(expDate,'71019')
    % THE NMF FILES WERE SAVED IN proc/analysisDuringExperiment/f71019_1/ WITH 
    % THE ENDINGS (4,3) BUT NOT THE STA AND CC ANALYSES
    ablationResults.nNotEye = 7+7;
    ablationResults.mapUsedOnline = {{'proc/analysisDuringExperiment/f71019_1/f71019_1_BMAP_4.fig','proc/analysisDuringExperiment/f71019_1/f71019_1_BMAP_3.fig'}};
    ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation'},'regImgInds',{[5,9]},'ablSequenceInds',{[{1:5},{6:9}]},...
        'targetImgCond',{[{'B'},{'B'}]},'targetImgInds',{[4,3]});
elseif strcmp(expDate,'71119')
    % THE NMF FILES WERE SAVED IN proc/analysisDuringExperiment/f71019_1/ WITH 
    % THE ENDINGS (4,3) BUT NOT THE STA AND CC ANALYSES
    if strcmp(options.animalNumber,'1')
        ablationResults.BImagesFormDVSequence = true;
        ablationResults.nNotEye = 7+4;
        ablationResults.mapUsedOnline = {{'proc/analysisDuringExperiment/f71119_1/f71119_1_BMAP_4.fig','proc/analysisDuringExperiment/f71119_1/f71119_1_BMAP_3.fig'}};
       
        ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation'},'regImgInds',{[5,9]},'ablSequenceInds',{[{1:5},{6:9}]},...
            'targetImgCond',{[{'B'},{'B'}]},'targetImgInds',{[4,3]});
    elseif strcmp(options.animalNumber,'2')
        ablationResults.BImagesFormDVSequence = true;
        ablationResults.nNotEye = 7+9;
        %ablationResults.mapUsedOnline =
        %{'proc/analysisDuringExperiment/f71119_2/f71119_2_BMAP_3.fig','proc/analysisDuringExperiment/f71119_2/f71119_2_BMAP_2.fig'}; % for some reason file BMAP_2 is corrupted and causes Matlab to crash
        ablationResults.mapUsedOnline = {{'proc/analysisDuringExperiment/f71119_2/f71119_2_BMAP_3.fig',[]}};
         ablationResults.duringAblReg = struct('nameConv',{'duringFirstAblation'},'regImgInds',{[4,11]},'ablSequenceInds',{[{1:4},{5:11}]},...
            'targetImgCond',{[{'B'},{'B'}]},'targetImgInds',{[3,2]});
    end
elseif strcmp(expDate,'71819')
    if strcmp(options.animalNumber,'1')
        ablationResults.nSRLHit = 5;
        ablationResults.nNotEye = 1+4;
        ablationResults.procDataEnding = {{'4'}};
        ablationResults.onlineProcDataPath = {{'proc/analysisDuringExperiment/f71819_1/'}};
        ablationResults.duringAblReg = struct('nameConv',{'during'},'regImgInds',{7},'ablSequenceInds',{{1:7}},...
            'targetImgCond',{{'B'}},'targetImgInds',{2});
        ablationResults.SRHitIDs = cell(5,1);
        ablationResults.SRHitIDs{1} = struct('procDataEnding','4','onlineProcDataPath','proc/analysisDuringExperiment/f71819_1/',...
            'XYPosition',[170.437,198.341],'hemiSphereLocation','Right Contra','ID',[2,67],'expCond','B',...
            'scAblationPhi',126.6,...
            'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f71819_1/during/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f71819_1/during/f71819_1_during_007.tif','ablationEvidenceFile','rawAvgStacks/f71819_1/during/f71819_1_002.tif',...
            'confidence','strong');
        
        ablationResults.SRHitIDs{2} = struct('procDataEnding','4','onlineProcDataPath','proc/analysisDuringExperiment/f71819_1/',...
            'XYPosition',[250.077,241.143],'hemiSphereLocation','Right Contra','ID',[2,123],'expCond','B',...
            'scAblationPhi',129.2,...
            'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f71819_1/during/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f71819_1/during/f71819_1_during_007.tif','ablationEvidenceFile','rawAvgStacks/f71819_1/during/f71819_1_003.tif',...
            'confidence','weak: bright spot does not last');
        
        ablationResults.SRHitIDs{3} = struct('procDataEnding','4','onlineProcDataPath','proc/analysisDuringExperiment/f71819_1/',...
            'XYPosition',[271.022,218.000],'hemiSphereLocation','Right Contra','ID',[2,132],'expCond','B',...
            'scAblationPhi',131.2,...
            'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f71819_1/during/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f71819_1/during/f71819_1_during_007.tif','ablationEvidenceFile','rawAvgStacks/f71819_1/during/f71819_1_004.tif',...
            'confidence','weak: bright spot does not last');
        
        ablationResults.SRHitIDs{4} = struct('procDataEnding','4','onlineProcDataPath','proc/analysisDuringExperiment/f71819_1/',...
            'XYPosition',[286.236,372.821],'hemiSphereLocation','Left Ipsi','ID',[2,154],'expCond','B',...
            'scAblationPhi',62.1,...
            'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f71819_1/during/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f71819_1/during/f71819_1_during_007.tif','ablationEvidenceFile','rawAvgStacks/f71819_1/during/f71819_1_005.tif',...
            'confidence','strong');
        
        ablationResults.SRHitIDs{5} = struct('procDataEnding','4','onlineProcDataPath','proc/analysisDuringExperiment/f71819_1/',...
            'XYPosition',[271.515,371.615],'hemiSphereLocation','Left Ipsi','ID',[2,94],'expCond','B',...
            'scAblationPhi',70.8,...
            'targetedXYPosition',[],'targetXYPositionFile','rawAvgStacks/f71819_1/during/',...
            'summaryEvidenceDamageFile','rawAvgStacks/f71819_1/during/f71819_1_during_007.tif','ablationEvidenceFile','rawAvgStacks/f71819_1/during/f71819_1_006.tif',...
            'confidence','strong');
    elseif strcmp(options.animalNumber,'2')
        %  sham ablation control (shutter was off)
    end
elseif strcmp(expDate,'71919')
    % sham ablation control (ablation power set to 0)
end